import json
from pathlib import Path


class ArtifactWriter:
    def __init__(self, output_base_dir: str) -> None:
        self.output_base_path = Path(output_base_dir)

    def write_step1_artifacts(self, *, patient_external_id: str, metadata: dict) -> str:
        """Write Step 1 artifacts: create the patient directory and persist metadata.json.

        Args:
            patient_external_id: Unique patient ID used as the output sub-directory name.
            metadata: Patient metadata dict generated by PatientMetadataGenerator.

        Returns:
            Absolute path to the patient output directory as a string.
        """
        patient_dir = self.output_base_path / patient_external_id
        patient_dir.mkdir(parents=True, exist_ok=True)

        # Write metadata.json directly into the patient directory
        metadata_path = patient_dir / "metadata.json"
        metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")

        return str(patient_dir)

    def write_step2_artifacts(
        self,
        *,
        patient_external_id: str,
        referral_text: str,
        medication_list: dict,
    ) -> str:
        """Write referral_packet.txt and medication_list.json (PRD 0A.2 Step 2 + 0A.4 Layer 1)."""
        patient_dir = self.output_base_path / patient_external_id
        patient_dir.mkdir(parents=True, exist_ok=True)

        (patient_dir / "referral_packet.txt").write_text(referral_text, encoding="utf-8")
        (patient_dir / "medication_list.json").write_text(
            json.dumps(medication_list, indent=2), encoding="utf-8"
        )

        return str(patient_dir)

    def write_step3_artifacts(
        self,
        *,
        patient_external_id: str,
        scribe_text: str,
    ) -> str:
        """Write ambient_scribe.txt (PRD 0A.2 Step 3)."""
        patient_dir = self.output_base_path / patient_external_id
        patient_dir.mkdir(parents=True, exist_ok=True)

        (patient_dir / "ambient_scribe.txt").write_text(scribe_text, encoding="utf-8")

        return str(patient_dir)

    def write_step4_artifacts(
        self,
        *,
        patient_external_id: str,
        gap_answers: dict,
    ) -> str:
        """Write tap_tap_gap_answers.json (PRD Step 4)."""
        patient_dir = self.output_base_path / patient_external_id
        patient_dir.mkdir(parents=True, exist_ok=True)

        (patient_dir / "tap_tap_gap_answers.json").write_text(
            json.dumps(gap_answers, indent=2), encoding="utf-8"
        )

        return str(patient_dir)

    def write_step5_artifacts(
        self,
        *,
        patient_external_id: str,
        oasis_gold_standard: dict,
    ) -> str:
        """Write oasis_gold_standard.json (PRD Step 6)."""
        patient_dir = self.output_base_path / patient_external_id
        patient_dir.mkdir(parents=True, exist_ok=True)

        (patient_dir / "oasis_gold_standard.json").write_text(
            json.dumps(oasis_gold_standard, indent=2), encoding="utf-8"
        )

        return str(patient_dir)

    def write_step6_artifacts(
        self,
        *,
        patient_external_id: str,
        validation_report: dict,
    ) -> str:
        """Write validation_report.json (PRD Step 7)."""
        patient_dir = self.output_base_path / patient_external_id
        patient_dir.mkdir(parents=True, exist_ok=True)

        (patient_dir / "validation_report.json").write_text(
            json.dumps(validation_report, indent=2), encoding="utf-8"
        )

        return str(patient_dir)
