"""Step 6 — OASIS Gold Standard Generator (oasis_gold_standard.json)

Generates a full OASIS-E1 gold-standard assessment in the oasis-llm-processor item-array format:
  [{"item_code", "value", "rationale", "confidence", "source"}, ...]

Flow:
  1. Copy all BIMS (C section) + PHQ-9 (D section) codes verbatim from tap_tap_gap_answers.json
     (source="gap_answers" — guaranteed consistent with Step 4, never regenerated by LLM)
  2. Query LLM in 5 clinical section batches (~20-50 codes each) for remaining OASIS-E1 fields
  3. Apply 8 deterministic CMS skip-logic rules post-batches
  4. Calculate HIP score from GG0130A1–E1 self-care admission performance codes

OUTPUT SHAPE:
  {
    "items": [{item_code, value, rationale, confidence, source}, ...],
    "validation": {bims_verified, bims_score, phq_verified, phq_score,
                   hip_score, hip_valid, skip_logic_applied},
    "source_documents": [...],
    "generated_at": "<ISO8601>"
  }
"""

import json
from datetime import datetime, timezone

from app.config.constants import (
    ADL_COPY_CODES,
    BIMS_COPY_CODES,
    GG0130_LABEL_TO_LETTER,
    GG0170_KEY_TO_LETTER,
    HIP_CODES,
    OASIS_SECTION_BATCHES,
    PHQ_COPY_CODES,
)
from app.services.llm.bedrock_client import BedrockClient
from app.config.prompts import OASIS_GOLD_STANDARD_PROMPT
from app.utils.json_utils import extract_json_array, repair_truncated_array
from app.utils.logger import get_logger

logger = get_logger(__name__)



def _item_value(item_map: dict[str, dict], code: str) -> str | None:
    """Safely extract the string value of an item from an item_map."""
    item = item_map.get(code)
    if item is None:
        return None
    val = item.get("value")
    return str(val).strip() if val is not None else None


class OasisGoldStandardGenerator:
    """Step 6 generator: produces a full OASIS-E1 gold-standard assessment dict."""

    def __init__(self) -> None:
        # Initialise the shared Bedrock LLM client.
        self.bedrock = BedrockClient()

    def generate(
        self,
        *,
        referral_text: str,
        medication_list: dict,
        scribe_text: str | None,
        gap_answers: dict,
        metadata: dict,
        model_id: str,
    ) -> dict:
        """Generate oasis_gold_standard.json content.

        Args:
            referral_text: Raw referral packet text from Step 2.
            medication_list: Medication list dict from Step 3.
            scribe_text: Ambient scribe text from Step 3b (or None).
            gap_answers: Gap answers dict from Step 4.
            metadata: Patient metadata dict from Step 1.
            model_id: AWS Bedrock model identifier string.

        Returns:
            Dict with keys: items, validation, source_documents, generated_at.
        """
        archetype = metadata.get("archetype", "chf_exacerbation")
        diagnosis_context = metadata.get("primary_diagnosis", archetype.replace("_", " ").title())

        # Step 1: Copy BIMS, PHQ, GG X1 admission codes, and M-ADL codes verbatim from
        #         gap_answers (never regenerated by LLM — PRD Step 4 is authoritative).
        bims_items = self._copy_from_gap_answers(gap_answers, BIMS_COPY_CODES)
        phq_items = self._apply_phq2_gate(
            self._copy_from_gap_answers(gap_answers, PHQ_COPY_CODES)
        )
        gg_adl_items = self._expand_gg_adl_from_gap_answers(gap_answers)
        logger.info(
            "Step 6: copied %d BIMS + %d PHQ + %d GG/ADL items from gap_answers",
            len(bims_items),
            len(phq_items),
            len(gg_adl_items),
        )

        # Step 2: Run 5 LLM section batches for all remaining OASIS fields.
        scribe_section = (
            f"--- AMBIENT SCRIBE (Nurse Visit Note) ---\n{scribe_text}"
            if scribe_text
            else "(No ambient scribe available for this patient)"
        )
        medication_summary = self._summarise_medication_list(medication_list)
        gap_context = self._build_gap_context(gap_answers)

        all_llm_items: list[dict] = []
        for section_name, codes in OASIS_SECTION_BATCHES:
            logger.info("Step 6: LLM batch %s (%d codes)", section_name, len(codes))
            batch_items = self._run_llm_batch(
                codes=codes,
                section_name=section_name,
                archetype=archetype,
                diagnosis_context=diagnosis_context,
                referral_text=referral_text,
                scribe_section=scribe_section,
                medication_summary=medication_summary,
                gap_context=gap_context,
                has_scribe="Yes" if scribe_text else "No",
                model_id=model_id,
            )
            all_llm_items.extend(batch_items)
            logger.info("Step 6: batch %s produced %d items", section_name, len(batch_items))

        # Build item_map: LLM items first, then Gap-derived items overwrite.
        # Priority (highest wins): BIMS/PHQ > GG/ADL (gap_answers) > LLM
        item_map: dict[str, dict] = {}
        for item in all_llm_items:
            code = item.get("item_code", "")
            if code:
                item_map[code] = item
        for item in gg_adl_items + bims_items + phq_items:
            item_map[item["item_code"]] = item

        # Step 3: Apply 8 CMS deterministic skip-logic rules.
        item_map, rules_applied = self._apply_skip_logic(item_map)
        logger.info("Step 6: skip-logic applied %d rule(s): %s", len(rules_applied), rules_applied)

        # Convert to sorted list and build output.
        final_items = sorted(item_map.values(), key=lambda x: x.get("item_code", ""))

        # Step 4: Build validation block.
        validation = self._build_validation(final_items, rules_applied)
        logger.info(
            "Step 6: validation — bims_score=%s phq_score=%s hip_score=%s hip_valid=%s",
            validation["bims_score"],
            validation["phq_score"],
            validation["hip_score"],
            validation["hip_valid"],
        )

        source_documents = ["referral_packet.txt", "medication_list.json"]
        if scribe_text:
            source_documents.append("ambient_scribe.txt")
        source_documents.append("tap_tap_gap_answers.json")

        return {
            "items": final_items,
            "validation": validation,
            "source_documents": source_documents,
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }

    # ── Private helpers ────────────────────────────────────────────────────────────────────

    @staticmethod
    def _apply_phq2_gate(phq_items: list[dict]) -> list[dict]:
        """Enforce the CMS PHQ-2 screening gate on a list of PHQ item dicts.

        Rule: If D0150A1 + D0150B1 < 3 the two-item screen is negative — items C–I
        (both symptom-presence X1 and frequency X2 codes) must be null/not-assessed,
        and D0160 is recalculated using only items A and B.

        Edits item dicts in-place and returns the same list.
        """
        by_code = {item["item_code"]: item for item in phq_items}

        a1_raw = by_code.get("D0150A1", {}).get("value")
        b1_raw = by_code.get("D0150B1", {}).get("value")
        if a1_raw is None or b1_raw is None:
            # Incomplete PHQ data — cannot evaluate gate
            return phq_items

        try:
            screen_score = int(str(a1_raw)) + int(str(b1_raw))
        except (ValueError, TypeError):
            return phq_items

        if screen_score >= 3:
            # Gate not triggered — full PHQ-9 was administered
            return phq_items

        # Gate fires: null out items C–I (symptoms not assessed)
        downstream_letters = ["C", "D", "E", "F", "G", "H", "I"]
        for letter in downstream_letters:
            for suffix in ("1", "2"):
                code = f"D0150{letter}{suffix}"
                item = by_code.get(code)
                if item is not None:
                    item["value"] = None
                    item["rationale"] = (
                        f"PHQ-2 screening score (D0150A1={a1_raw} + D0150B1={b1_raw} = "
                        f"{screen_score}) < 3 — PHQ-9 items C–I are not administered "
                        f"(CMS skip-logic gate). Original gap_answers value nulled by "
                        f"oasis_gold_standard_generator._apply_phq2_gate()."
                    )
                    item["confidence"] = "high"

        # Recalculate D0160: sum of frequency (X2) only for items present (X1 != "0") among A and B
        freq_sum = 0
        for letter in ("A", "B"):
            symptom = by_code.get(f"D0150{letter}1", {}).get("value")
            freq = by_code.get(f"D0150{letter}2", {}).get("value")
            if symptom is not None and str(symptom).strip() != "0" and freq is not None:
                try:
                    freq_sum += int(str(freq))
                except (ValueError, TypeError):
                    pass

        d0160 = by_code.get("D0160")
        if d0160 is not None:
            old_value = d0160.get("value")
            d0160["value"] = str(freq_sum)
            d0160["rationale"] = (
                f"PHQ-2 gate applied: screen score {screen_score} < 3. "
                f"D0160 recalculated as sum of frequency codes for present items A–B only "
                f"(was {old_value} in gap_answers; corrected to {freq_sum})."
            )
            d0160["confidence"] = "high"

        logger.info(
            "PHQ-2 gate applied (screen=%d): items C–I nulled, D0160 corrected to %d",
            screen_score,
            freq_sum,
        )
        return phq_items

    def _copy_from_gap_answers(self, gap_answers: dict, codes: list[str]) -> list[dict]:
        """Copy a list of codes verbatim from gap_answers.unanswered_response.

        Args:
            gap_answers: Full gap answers dict from Step 4.
            codes: List of OASIS item codes to copy.

        Returns:
            List of item dicts with source="gap_answers".
        """
        unanswered = gap_answers.get("unanswered_response", {})
        items: list[dict] = []
        for code in codes:
            entry = unanswered.get(code)
            if entry:
                answer = entry.get("answer")
                items.append({
                    "item_code": code,
                    "value": str(answer) if answer is not None else None,
                    "rationale": (
                        f"Copied verbatim from tap_tap_gap_answers.json (Step 4 assessment). "
                        f"Question: {entry.get('question', code)}"
                    ),
                    "confidence": "high",
                    "source": "gap_answers",
                })
            else:
                logger.warning(
                    "Step 6: %s not found in gap_answers unanswered_response — skipping",
                    code,
                )
        return items

    def _expand_gg_adl_from_gap_answers(self, gap_answers: dict) -> list[dict]:
        """Derive GG0130 X1 admission codes, GG0170 X1 admission codes, and M-ADL codes from
        Step 4 gap answers.

        PRD rule: GG admission performance values ARE validated in Step 4 and must
        propagate unchanged into the gold standard.  This method is authoritative —
        the LLM must not override these values.

        GG0130 is stored as a grouped dict {"Eating": "05", ...}; each label maps to
        a specific X1 code.  GG0170 is stored as {"A": "04", ...}; each key maps to
        the corresponding X1 code.  M-ADL codes are stored as individual entries.
        """
        unanswered = gap_answers.get("unanswered_response", {})
        items: list[dict] = []

        # ── GG0130 Self-Care X1 (admission performance) ───────────────────────────────────
        gg0130_entry = unanswered.get("GG0130")
        if gg0130_entry and isinstance(gg0130_entry.get("answer"), dict):
            gg0130_dict: dict = gg0130_entry["answer"]
            for label, letter_or_letters in GG0130_LABEL_TO_LETTER.items():
                val = gg0130_dict.get(label)
                if val is not None:
                    # letter_or_letters may be a single letter or a list (e.g. "Dressing" -> D+E)
                    letters = (
                        letter_or_letters
                        if isinstance(letter_or_letters, list)
                        else [letter_or_letters]
                    )
                    for letter in letters:
                        code = f"GG0130{letter}1"
                        items.append({
                            "item_code": code,
                            "value": str(val),
                            "rationale": (
                                f"Expanded from Step 4 gap answers: "
                                f"tap_tap_gap_answers.GG0130['{label}'] = {val}.  "
                                f"(GG0130A1 is not stored directly; derived from the "
                                f"grouped GG0130 answer dict.)  "
                                f"PRD: GG admission performance is validated in Step 4."
                            ),
                            "confidence": "high",
                            "source": "gap_answers",
                        })
        else:
            logger.warning(
                "Step 6: GG0130 grouped dict not found in gap_answers — "
                "GG0130 X1 codes will fall through to LLM"
            )

        # ── GG0170 Mobility X1 (admission performance) ────────────────────────────────────
        gg0170_entry = unanswered.get("GG0170")
        if gg0170_entry and isinstance(gg0170_entry.get("answer"), dict):
            gg0170_dict: dict = gg0170_entry["answer"]
            # Track which letters have been written to avoid duplicate items when
            # multiple snake_case keys map to the same letter (e.g. roll_left / roll_right).
            seen_letters: set[str] = set()
            for key, val in gg0170_dict.items():
                letter = GG0170_KEY_TO_LETTER.get(key)
                if letter is None:
                    logger.warning("Step 6: unknown GG0170 key %r — skipping", key)
                    continue
                if letter in seen_letters:
                    continue
                seen_letters.add(letter)
                if val is not None:
                    code = f"GG0170{letter}1"
                    items.append({
                        "item_code": code,
                        "value": str(val),
                        "rationale": (
                            f"Expanded from Step 4 gap answers: "
                            f"tap_tap_gap_answers.GG0170['{key}'] = {val}.  "
                            f"(GG0170{letter}1 is not stored directly; derived from "
                            f"the grouped GG0170 answer dict.)  "
                            f"PRD: GG admission performance is validated in Step 4."
                        ),
                        "confidence": "high",
                        "source": "gap_answers",
                    })
        else:
            logger.warning(
                "Step 6: GG0170 grouped dict not found in gap_answers — "
                "GG0170 X1 codes will fall through to LLM"
            )

        # ── ADL M-codes ───────────────────────────────────────────────────────────────────
        for code in ADL_COPY_CODES:
            entry = unanswered.get(code)
            if entry:
                answer = entry.get("answer")
                items.append({
                    "item_code": code,
                    "value": str(answer) if answer is not None else None,
                    "rationale": (
                        f"Copied verbatim from tap_tap_gap_answers.json (Step 4 assessment). "
                        f"Question: {entry.get('question', code)}"
                    ),
                    "confidence": "high",
                    "source": "gap_answers",
                })
            else:
                logger.warning(
                    "Step 6: %s not found in gap_answers unanswered_response — skipping",
                    code,
                )

        logger.info(
            "Step 6: _expand_gg_adl_from_gap_answers produced %d items "
            "(GG0130=%d, GG0170=%d, ADL=%d)",
            len(items),
            sum(1 for i in items if i["item_code"].startswith("GG0130")),
            sum(1 for i in items if i["item_code"].startswith("GG0170")),
            sum(1 for i in items if not i["item_code"].startswith("GG")),
        )
        return items

    @staticmethod
    def _summarise_medication_list(medication_list: dict) -> str:
        """Extract a compact summary of active medications from Layer 1 for prompt context."""
        try:
            layer1 = medication_list.get("layer1") or medication_list
            meds = layer1.get("medications") or []
            if meds:
                names = []
                for m in meds[:15]:
                    name = (
                        m.get("name")
                        or m.get("medication_name")
                        or m.get("drug_name")
                        or str(m)
                    )
                    if name:
                        names.append(name)
                return "Active medications: " + ", ".join(names)
        except Exception:
            pass
        return "(Medication list unavailable)"

    @staticmethod
    def _build_gap_context(gap_answers: dict) -> str:
        """Build a comprehensive Step 4 context block for the LLM prompt.

        Includes BIMS total, PHQ total, ALL individual GG0130/GG0170 sub-items,
        ADL M-codes, and key functional codes.  The LLM MUST use these as the
        authoritative source — it must not re-derive GG discharge goals
        independently (PRD Step 4 rule: GG goals require clinical judgment and
        are never extractable from referral/scribe).
        """
        unanswered = gap_answers.get("unanswered_response", {})
        lines: list[str] = []

        # ── Top-level scores ───────────────────────────────────────────────────
        for code, label in [
            ("C0500", "BIMS Total (C0500)"),
            ("D0160", "PHQ-9 Total (D0160)"),
        ]:
            entry = unanswered.get(code)
            if entry:
                lines.append(f"{label}: {entry.get('answer', 'N/A')}")

        # ── GG0130 Self-Care — expand grouped dict or individual sub-codes ────
        gg0130_entry = unanswered.get("GG0130")
        if gg0130_entry and isinstance(gg0130_entry.get("answer"), dict):
            # Step 4 stores as a grouped object: {"Eating": "05", "Oral Hygiene": "04", ...}
            lines.append("GG0130 Self-Care (Step 4 grouped answers):")
            for sub, val in gg0130_entry["answer"].items():
                lines.append(f"  GG0130 {sub}: {val}")
        else:
            # Try individual sub-codes (if stored that way)
            for letter in ["A", "B", "C", "D", "E", "F", "G"]:
                for suffix in ["1", "2"]:
                    code = f"GG0130{letter}{suffix}"
                    entry = unanswered.get(code)
                    if entry:
                        lines.append(f"  {code}: {entry.get('answer', 'N/A')}")

        # ── GG0170 Mobility — expand grouped dict or individual sub-codes ─────
        gg0170_entry = unanswered.get("GG0170")
        if gg0170_entry and isinstance(gg0170_entry.get("answer"), dict):
            lines.append("GG0170 Mobility (Step 4 grouped answers):")
            for sub, val in gg0170_entry["answer"].items():
                lines.append(f"  GG0170 {sub}: {val}")
        else:
            for letter in ["A", "B", "C", "D", "E", "F", "G", "I", "J", "K", "L", "M", "N", "O", "P"]:
                for suffix in ["1", "2"]:
                    code = f"GG0170{letter}{suffix}"
                    entry = unanswered.get(code)
                    if entry:
                        lines.append(f"  {code}: {entry.get('answer', 'N/A')}")

        # GG0170C prior function
        gg0170c = unanswered.get("GG0170C")
        if gg0170c:
            lines.append(f"GG0170C prior walking: {gg0170c.get('answer', 'N/A')}")

        # ── GG0100 Prior Functioning ──────────────────────────────────────────
        gg0100_entry = unanswered.get("GG0100")
        if gg0100_entry and isinstance(gg0100_entry.get("answer"), dict):
            lines.append("GG0100 Prior Functioning (Step 4):")
            for sub, val in gg0100_entry["answer"].items():
                lines.append(f"  {sub}: {val}")

        # ── ADL M-codes from Step 4 ───────────────────────────────────────────
        adl_codes = [
            "M1800", "M1810", "M1820", "M1830", "M1840",
            "M1845", "M1850", "M1860", "M1870", "M1880",
            "M1890", "M1900", "M1910",
        ]
        adl_lines = []
        for code in adl_codes:
            entry = unanswered.get(code)
            if entry:
                adl_lines.append(f"  {code}: {entry.get('answer', 'N/A')}")
        if adl_lines:
            lines.append("ADL M-codes (Step 4):")
            lines.extend(adl_lines)

        # ── Cognitive / Behavioral ────────────────────────────────────────────
        for code in ["M1700", "M1710", "M1720", "M1740", "M1400"]:
            entry = unanswered.get(code)
            if entry:
                lines.append(f"{code}: {entry.get('answer', 'N/A')}")

        return "\n".join(lines) if lines else "(No gap assessment context available)"

    def _run_llm_batch(
        self,
        *,
        codes: list[str],
        section_name: str,
        archetype: str,
        diagnosis_context: str,
        referral_text: str,
        scribe_section: str,
        medication_summary: str,
        gap_context: str,
        has_scribe: str,
        model_id: str,
    ) -> list[dict]:
        """Run one LLM batch and return a list of OASIS item dicts.

        Args:
            codes: List of OASIS item codes for this batch.
            section_name: Human-readable batch name used in logging and prompt.
            archetype: Patient clinical archetype string.
            diagnosis_context: Primary diagnosis description.
            referral_text: Full referral packet text.
            scribe_section: Formatted ambient scribe text block (or placeholder string).
            medication_summary: Compact medication list summary string.
            gap_context: Step 4 gap context block string.
            has_scribe: "Yes" or "No" string for the prompt.
            model_id: AWS Bedrock model identifier.

        Returns:
            List of item dicts (item_code, value, rationale, confidence, source).
        """
        prompt = OASIS_GOLD_STANDARD_PROMPT.format(
            archetype=archetype,
            diagnosis_context=diagnosis_context,
            has_scribe=has_scribe,
            section_name=section_name,
            referral_text=referral_text,
            scribe_section=scribe_section,
            medication_summary=medication_summary,
            gap_context=gap_context,
            field_codes_json=json.dumps(codes, indent=2),
        )
        response = self.bedrock.invoke_json(
            prompt=prompt,
            model_id=model_id,
            max_tokens=4096,
        )
        text = response["text"].strip()

        try:
            raw = json.loads(extract_json_array(text))
        except Exception as exc:
            logger.error(
                "Step 6 batch %s JSON parse failed (%s) — attempting repair",
                section_name,
                exc,
            )
            raw = repair_truncated_array(text)

        if not isinstance(raw, list):
            logger.warning("Step 6 batch %s: LLM returned non-array — wrapping", section_name)
            if isinstance(raw, dict):
                raw = [{"item_code": k, **v} for k, v in raw.items()]
            else:
                raw = []

        seen_codes: set[str] = set()
        batch_items: list[dict] = []
        for entry in raw:
            if not isinstance(entry, dict):
                continue
            code = str(entry.get("item_code") or "").strip().upper()
            if not code or code in seen_codes:
                continue
            seen_codes.add(code)
            batch_items.append({
                "item_code": code,
                "value": entry.get("value"),
                "rationale": str(entry.get("rationale") or ""),
                "confidence": str(entry.get("confidence") or "medium"),
                "source": "llm",
            })

        # Fill in placeholder items for any codes not returned by the LLM.
        for code in codes:
            if code not in seen_codes:
                logger.warning(
                    "Step 6 batch %s: no item for %s — inserting placeholder",
                    section_name,
                    code,
                )
                batch_items.append({
                    "item_code": code,
                    "value": None,
                    "rationale": f"Not returned by LLM for batch {section_name}",
                    "confidence": "low",
                    "source": "llm",
                })

        return batch_items

    def _apply_skip_logic(
        self, item_map: dict[str, dict]
    ) -> tuple[dict[str, dict], list[str]]:
        """Apply 8 deterministic CMS skip-logic rules.

        Args:
            item_map: Dict of item_code -> item dict.

        Returns:
            Tuple of (modified item_map, list of rule names applied).
        """
        rules_applied: list[str] = []

        # ── 1. BIMS_GATE: C0100=0 → null BIMS sub-scores ─────────────────────────────────
        if _item_value(item_map, "C0100") == "0":
            bims_downstream = [
                "C0200", "C0300A", "C0300B", "C0300C",
                "C0400A", "C0400B", "C0400C", "C0500",
            ]
            modified = any(
                item_map[c].get("value") is not None
                for c in bims_downstream
                if c in item_map
            )
            for code in bims_downstream:
                if code in item_map:
                    item_map[code]["value"] = None
                    item_map[code]["rationale"] = "Skip: C0100=0 (BIMS was not administered)"
            if modified:
                rules_applied.append("BIMS_GATE")

        # ── 2. PHQ_GATE: D0150A1=9 AND D0150B1=9 → null all downstream PHQ ──────────────
        if _item_value(item_map, "D0150A1") == "9" and _item_value(item_map, "D0150B1") == "9":
            phq_downstream = [
                "D0150C1", "D0150C2", "D0150D1", "D0150D2",
                "D0150E1", "D0150E2", "D0150F1", "D0150F2",
                "D0150G1", "D0150G2", "D0150H1", "D0150H2",
                "D0150I1", "D0150I2", "D0160",
            ]
            for code in phq_downstream:
                if code in item_map:
                    item_map[code]["value"] = None
                    item_map[code]["rationale"] = (
                        "Skip: PHQ-2 screening negative (D0150A1=9, D0150B1=9)"
                    )
            rules_applied.append("PHQ_GATE")

        # ── 3. PHQ_COL2_GATE: each D0150X1=0 → D0150X2=null ─────────────────────────────
        phq_col2_modified = False
        for letter in ["A", "B", "C", "D", "E", "F", "G", "H", "I"]:
            col1 = f"D0150{letter}1"
            col2 = f"D0150{letter}2"
            if _item_value(item_map, col1) == "0" and col2 in item_map:
                item_map[col2]["value"] = None
                item_map[col2]["rationale"] = (
                    f"Skip: {col1}=0 (symptom not present; frequency column N/A)"
                )
                phq_col2_modified = True
        if phq_col2_modified:
            rules_applied.append("PHQ_COL2_GATE")

        # ── 4. M1306_ULCER: M1306=0 → wound staging items = "0" ─────────────────────────
        if _item_value(item_map, "M1306") == "0":
            for code in ["M1311", "M1312", "M1313", "M1314"]:
                if code in item_map:
                    item_map[code]["value"] = "0"
                    item_map[code]["rationale"] = (
                        "Skip: M1306=0 (no unhealed pressure ulcer at Stage 2+)"
                    )
            rules_applied.append("M1306_ULCER")

        # ── 5. M1330_STASIS: M1330=0 → null M1332, M1334 ────────────────────────────────
        if _item_value(item_map, "M1330") == "0":
            for code in ["M1332", "M1334"]:
                if code in item_map:
                    item_map[code]["value"] = None
                    item_map[code]["rationale"] = "Skip: M1330=0 (no stasis ulcer present)"
            rules_applied.append("M1330_STASIS")

        # ── 6. GG_WALK_HIERARCHY: GG0170I1 unable → skip J/K/L walk items ────────────────
        i1_val = _item_value(item_map, "GG0170I1")
        if i1_val in {"07", "09", "10", "88"}:
            for code in ["GG0170J1", "GG0170K1", "GG0170L1"]:
                if code in item_map:
                    item_map[code]["value"] = "88"
                    item_map[code]["rationale"] = (
                        f"Skip: GG0170I1={i1_val} — patient cannot walk 10 ft; "
                        "longer walking activities not attempted"
                    )
            rules_applied.append("GG_WALK_HIERARCHY")

        # ── 7. GG_STAIR_HIERARCHY: GG0170M1 unable → skip N/O stair items ───────────────
        m1_val = _item_value(item_map, "GG0170M1")
        if m1_val in {"07", "09", "10", "88"}:
            for code in ["GG0170N1", "GG0170O1"]:
                if code in item_map:
                    item_map[code]["value"] = "88"
                    item_map[code]["rationale"] = (
                        f"Skip: GG0170M1={m1_val} — patient cannot climb 1 step; "
                        "multi-step stair activities not attempted"
                    )
            rules_applied.append("GG_STAIR_HIERARCHY")

        # ── 8. M1740_EXCLUSIVE: code "7" (None of above) is exclusive ────────────────────
        m1740_val = _item_value(item_map, "M1740")
        if m1740_val is not None and "7" in str(m1740_val):
            if "M1740" in item_map:
                item_map["M1740"]["value"] = "7"
                item_map["M1740"]["rationale"] = (
                    "M1740 None-of-above (7) is exclusive: other behavioral symptoms cleared"
                )
            rules_applied.append("M1740_EXCLUSIVE")

        return item_map, rules_applied

    def _build_validation(self, items: list[dict], rules_applied: list[str]) -> dict:
        """Build the validation block from the final item list.

        Args:
            items: Final sorted list of OASIS item dicts.
            rules_applied: List of skip-logic rule names that were applied.

        Returns:
            Dict with bims_verified, bims_score, phq_verified, phq_score,
            hip_score, hip_valid, skip_logic_applied.
        """
        item_map = {i["item_code"]: i for i in items}

        # BIMS score from C0500
        bims_score: int | None = None
        bims_verified = False
        c0500 = item_map.get("C0500")
        if c0500 and c0500.get("value") is not None:
            try:
                bims_score = int(str(c0500["value"]).strip().split()[0])
                bims_verified = 0 <= bims_score <= 15
            except (ValueError, TypeError):
                pass

        # PHQ score from D0160
        phq_score: int | None = None
        phq_verified = False
        d0160 = item_map.get("D0160")
        if d0160 and d0160.get("value") is not None:
            try:
                phq_score = int(str(d0160["value"]).strip().split()[0])
                phq_verified = 0 <= phq_score <= 27
            except (ValueError, TypeError):
                pass

        # HIP score from GG0130A1–E1
        hip_score, hip_valid = self._calculate_hip(item_map)

        return {
            "bims_verified": bims_verified,
            "bims_score": bims_score,
            "phq_verified": phq_verified,
            "phq_score": phq_score,
            "hip_score": hip_score,
            "hip_valid": hip_valid,
            "skip_logic_applied": rules_applied,
        }

    @staticmethod
    def _calculate_hip(item_map: dict[str, dict]) -> tuple:
        """Calculate HIP score: sum of GG0130A1–E1 self-care admission performance codes (5–30).

        Returns:
            Tuple of (hip_score: int | None, hip_valid: bool).
        """
        scores: list[int] = []
        for code in HIP_CODES:
            item = item_map.get(code)
            if item is None or item.get("value") is None:
                return None, False
            try:
                val = int(str(item["value"]).strip().split()[0])
                if not (1 <= val <= 6):
                    return None, False
                scores.append(val)
            except (ValueError, TypeError):
                return None, False
        return sum(scores), True
