"""Step 6 — OASIS Gold Standard Generator (oasis_gold_standard.json)

Generates a full OASIS-E1 gold-standard assessment in the oasis-llm-processor item-array format:
  [{"item_code", "value", "rationale", "confidence", "source"}, ...]

Flow:
  1. Copy all BIMS (C section) + PHQ-9 (D section) codes verbatim from tap_tap_gap_answers.json
     (source="gap_answers" — guaranteed consistent with Step 4, never regenerated by LLM)
  2. Query LLM in 5 clinical section batches (~20-50 codes each) for remaining OASIS-E1 fields
  3. Apply 8 deterministic CMS skip-logic rules post-batches
  4. Calculate HIP score from GG0130A1–E1 self-care admission performance codes

OUTPUT SHAPE:
  {
    "M1021": "I10",
    "M1023_1": "E11.9",
    ...
  }
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
import logging
from typing import Any

from app.config.constants import (
    ADL_COPY_CODES,
    BIMS_COPY_CODES,
    GG0130_LABEL_TO_LETTER,
    GG0170_KEY_TO_LETTER,
    HIP_CODES,
    OASIS_SECTION_BATCHES,
    PHQ_COPY_CODES,
    WOUND_ARCHETYPES,
    WOUND_CODES,
)
from app.services.llm.bedrock_client import BedrockClient
from app.config.prompts import (
    GOLD_SECTION_FIX_PROMPT,
    GOLD_SECTION_PROMPT_MAP,
    OASIS_GOLD_STANDARD_PROMPT,
)
from app.utils.json_utils import extract_json_object, repair_truncated_json
from app.utils.logger import get_logger
from app.utils.gap_answers_utils import lookup_gap_answer as _lookup_gap_answer
from app.utils.oasis_validators import validate_batch

logger = get_logger(__name__)

def _item_value(item_map: dict[str, dict], code: str) -> str | None:
    """Safely extract the string value of an item from an item_map."""
    item = item_map.get(code)
    if item is None:
        return None
    val = item.get("value")
    return str(val).strip() if val is not None else None


class OasisGoldStandardGenerator:
    """Step 6 generator: produces a full OASIS-E1 gold-standard assessment dict."""

    def __init__(self) -> None:
        # Initialise the shared Bedrock LLM client.
        self.bedrock = BedrockClient()
        # Load oasis_config.json for per-group coding guidance injection.
        self._oasis_config_groups: list[dict] = self._load_oasis_config()
        # Build field_code → group_guidance lookup (only real OASIS groups).
        self._field_guidance_map: dict[str, str] = {}
        self._field_group_name_map: dict[str, str] = {}
        for group in self._oasis_config_groups:
            guidance = group.get("group_guidance", "")
            group_name = group.get("group_name", "")
            if not guidance:
                continue
            for field in group.get("fields", []):
                self._field_guidance_map[field] = guidance
                self._field_group_name_map[field] = group_name

    @staticmethod
    def _load_oasis_config() -> list[dict]:
        """Load oasis_config.json from the app config directory.

        Returns empty list on failure so the generator degrades gracefully.
        """
        import os
        config_dir = os.path.join(os.path.dirname(__file__), "..", "..", "config")
        default_path = os.path.normpath(os.path.join(config_dir, "oasis_config.json"))
        path = os.environ.get("OASIS_CONFIG_PATH", default_path)
        try:
            with open(path, encoding="utf-8") as fh:
                data = json.load(fh)
            if isinstance(data, list):
                logger.info(
                    "OasisGoldStandardGenerator: loaded oasis_config with %d groups from %s",
                    len(data), path,
                )
                return data
        except FileNotFoundError:
            logger.warning(
                "OasisGoldStandardGenerator: oasis_config.json not found at %s — "
                "per-group coding guidance will not be injected",
                path,
            )
        except Exception as exc:
            logger.error("OasisGoldStandardGenerator: failed to load oasis_config: %s", exc)
        return []

    def _build_oasis_guidance_for_codes(self, codes: list[str]) -> str:
        """Return consolidated group_guidance text for all oasis_config groups
        whose fields overlap with *codes*.

        Groups are de-duplicated; only groups that have non-empty guidance and
        contain at least one real OASIS code (not non_oasis_*) are included.
        """
        seen_guidances: dict[str, str] = {}  # group_name → guidance
        for code in codes:
            group_name = self._field_group_name_map.get(code)
            guidance = self._field_guidance_map.get(code)
            if group_name and guidance and group_name not in seen_guidances:
                seen_guidances[group_name] = guidance
        if not seen_guidances:
            return ""
        parts = [
            f"### {name}\n{text}" for name, text in seen_guidances.items()
        ]
        return "\n\n".join(parts)

    def generate(
        self,
        *,
        referral_text: str,
        medication_list: dict,
        scribe_text: str | None,
        gap_answers: dict,
        metadata: dict,
        model_id: str,
        audit_context: str | None = None,
    ) -> dict:
        """Generate oasis_gold_standard.json content.

        Args:
            referral_text: Raw referral packet text from Step 2.
            medication_list: Medication list dict from Step 3.
            scribe_text: Ambient scribe text from Step 3b (or None).
            gap_answers: Gap answers dict from Step 4.
            metadata: Patient metadata dict from Step 1.
            model_id: AWS Bedrock model identifier string.
            audit_context: Optional conflict summary from a previous LLM audit run.

        Returns:
            Dict with keys: items, validation, source_documents, generated_at.
        """
        archetype = metadata.get("archetype", "chf_exacerbation")
        diagnosis_context = metadata.get("primary_diagnosis", archetype.replace("_", " ").title())

        # Step 1: Copy BIMS, PHQ, GG X1 admission codes, and M-ADL codes verbatim from
        #         gap_answers (never regenerated by LLM — PRD Step 4 is authoritative).
        bims_items = self._correct_bims_arithmetic(
            self._copy_from_gap_answers(gap_answers, BIMS_COPY_CODES)
        )
        phq_items = self._apply_phq2_gate(
            self._copy_from_gap_answers(gap_answers, PHQ_COPY_CODES)
        )
        gg_adl_items = self._expand_gg_adl_from_gap_answers(gap_answers)
        n0415_items = (
            self._derive_n0415_from_gap_sub_codes(gap_answers)
            or self._derive_n0415_from_medication_list(medication_list)
            or self._decompose_n0415_from_gap_answers(gap_answers)
        )
        logger.info(
            "Step 6: copied %d BIMS + %d PHQ + %d GG/ADL + %d N0415 items from gap_answers",
            len(bims_items),
            len(phq_items),
            len(gg_adl_items),
            len(n0415_items),
        )

        # Step 2: Run 5 LLM section batches for all remaining OASIS fields.
        scribe_section = (
            f"--- AMBIENT SCRIBE (Nurse Visit Note) ---\n{scribe_text}"
            if scribe_text
            else "(No ambient scribe available for this patient)"
        )
        medication_json = json.dumps(medication_list, indent=2) if medication_list else "(Medication list unavailable)"
        gap_context = self._build_gap_context(gap_answers)

        all_llm_items: list[dict] = []
        groups_completed = 0
        groups_failed = 0
        for section_name, codes in OASIS_SECTION_BATCHES:
            # PRD: Clinical archetype based filtering.
            # If patient is not wound-bearing, omit wound-specific codes from the batch request.
            filtered_codes = codes
            if archetype not in WOUND_ARCHETYPES:
                filtered_codes = [c for c in codes if c not in WOUND_CODES]

            if not filtered_codes:
                logger.info("Step 6: Skipping LLM batch %s (no relevant codes for archetype %s)", section_name, archetype)
                continue

            logger.info("Step 6: LLM batch %s (%d codes requested)", section_name, len(filtered_codes))
            batch_items = self._generate_and_fix_section_batch(
                codes=filtered_codes,
                section_name=section_name,
                archetype=archetype,
                diagnosis_context=diagnosis_context,
                referral_text=referral_text,
                scribe_section=scribe_section,
                medication_json=medication_json,
                gap_context=gap_context,
                has_scribe="Yes" if scribe_text else "No",
                model_id=model_id,
                audit_context=audit_context,
            )
            all_llm_items.extend(batch_items)
            groups_completed += 1
            logger.info("Step 6: batch %s produced %d items", section_name, len(batch_items))

        # Build item_map: LLM items first, then Gap-derived items overwrite.
        # Priority (highest wins): BIMS/PHQ > GG/ADL (gap_answers) > LLM
        item_map: dict[str, dict] = {}
        for item in all_llm_items:
            code = item.get("item_code", "")
            if code:
                item_map[code] = item
        for item in gg_adl_items + bims_items + phq_items + n0415_items:
            item_map[item["item_code"]] = item

        # Step 3: Apply 8 CMS deterministic skip-logic rules.
        item_map, rules_applied = self._apply_skip_logic(item_map)
        logger.info("Step 6: skip-logic applied %d rule(s): %s", len(rules_applied), rules_applied)

        # Convert to sorted list and build output.
        final_items = sorted(item_map.values(), key=lambda x: x.get("item_code", ""))

        # Step 4: Build validation block.
        validation = self._build_validation(final_items, rules_applied)
        logger.info(
            "Step 6: validation — bims_score=%s phq_score=%s hip_score=%s hip_valid=%s",
            validation["bims_score"],
            validation["phq_score"],
            validation["hip_score"],
            validation["hip_valid"],
        )

        # PRD Section 2.3 format: a flat key-value object mapping every OASIS item code to its correct value.
        # Format matches SYN_0024 reference: includes metadata fields + _items_detail rationale array.
        _METADATA_KEYS = {"patient_id", "generated_at", "use_rag", "groups_completed", "groups_failed", "total_fields"}
        output_dict: dict = {
            "_generated": True,
            "_note": "SYNTHETIC \u2014 NOT REAL PATIENT DATA",
            "patient_id": metadata.get("patient_id", "UNKNOWN"),
            "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f") + "Z",
            "use_rag": True,
            "groups_completed": groups_completed,
            "groups_failed": groups_failed,
        }

        # Non-OASIS narrative keys that should never appear in the gold standard output.
        # These are sometimes hallucinated by the LLM from EHR context.
        _NON_OASIS_BLOCKED: set[str] = {
            "PHQ_MOOD_INTERVIEW", "ALLERGIES", "VITAL_SIGNS", "DIABETIC_FOOT",
            "COMMUNITY_SCREENING", "CORRECTIVE_ACTION_PLAN", "CIRCULATORY_HISTORY",
            "MENTAL_STATUS", "SKIN", "ACTIVITIES_PERMITTED", "MEDICATIONS",
            "NUTRITIONAL_REQUIREMENTS", "SAFETY_MEASURES", "DISCHARGE_PLANNING",
        }
        
        # Parent codes that often have specific sub-codes and should be filtered out if null
        # to keep the JSON strictly terminal.
        # e.g. M1023 is a parent, M1023_1 is specific.
        parent_codes = {
            "K0520", "M1021", "M1023", "M1028", "M1030", "M1033", 
            "M1060", "M2102", "O0110", "D0150", "C0300", "C0400"
        }

        for item in final_items:
            code = item["item_code"]
            val = item.get("value")

            # Hard-block non-OASIS narrative codes
            if code in _NON_OASIS_BLOCKED:
                logger.warning("Step 6: dropping non-OASIS code %s from output", code)
                continue

            # Validate A1005 (Ethnicity) — must be "1" or "2", not a state code or other value
            if code == "A1005" and val is not None:
                val_str = str(val).strip()
                if val_str not in ("1", "2"):
                    logger.warning(
                        "Step 6: A1005 value %r invalid (expected 1 or 2 for ethnicity) — clearing",
                        val_str,
                    )
                    val = None

            # Validate A1010 (Race) — must be a 1-2 digit numeric code 1–6 or 99, not a date/ZIP/state
            if code == "A1010" and val is not None:
                val_str = str(val).strip()
                if "/" in val_str or len(val_str) > 3 or not val_str.isdigit():
                    logger.warning(
                        "Step 6: A1010 value %r looks invalid (expected race code 1–6 or 99) — clearing",
                        val_str,
                    )
                    val = None

            # Validate A1110 (Preferred language) — must be a 2-letter language code, not a date or name
            if code == "A1110" and val is not None:
                val_str = str(val).strip()
                import re as _re
                # Date pattern or purely numeric → wrong field
                if _re.match(r"\d{1,2}[/-]\d{1,2}[/-]\d{4}", val_str) or val_str.isdigit():
                    logger.warning(
                        "Step 6: A1110 value %r looks like a date/number, not a language code — clearing",
                        val_str,
                    )
                    val = None
                elif len(val_str) > 5:
                    # Language codes are 2-3 chars (EN, SP, OT); longer values are free-text
                    logger.warning(
                        "Step 6: A1110 value %r too long for a language code — clearing",
                        val_str,
                    )
                    val = None

            # Validate clinical date fields — must be a plausible care-episode date (year >= 2000).
            # LLMs sometimes place the patient DOB (e.g. "06/14/1946") into fields like M0104.
            _CLINICAL_DATE_CODES = {"M0080", "M0090", "M0100", "M0102", "M0104", "M0110", "M1005"}
            if code in _CLINICAL_DATE_CODES and val is not None:
                val_str = str(val).strip()
                import re as _re
                m_date = _re.match(r"(\d{1,2})[/-](\d{1,2})[/-](\d{4})$", val_str)
                if m_date:
                    year = int(m_date.group(3))
                    if year < 2000:
                        logger.warning(
                            "Step 6: %s value %r has year %d < 2000 — looks like a birthdate, clearing",
                            code, val_str, year,
                        )
                        val = None
            
            # Skip parent codes if they are null or empty (they have sub-codes like M1023_1)
            if code in parent_codes and (val is None or str(val).strip() == ""):
                continue

            output_dict[code] = val

        # Set total_fields = count of OASIS field codes only (excludes metadata and underscore keys).
        output_dict["total_fields"] = sum(
            1 for k in output_dict
            if not k.startswith("_") and k not in _METADATA_KEYS
        )

        # O0110 fields are binary 0/1 flags; normalise any "NA" the LLM wrote to "0".
        for key in list(output_dict.keys()):
            if key.startswith("O0110") and output_dict[key] == "NA":
                output_dict[key] = "0"

        # Append _items_detail: full rationale + confidence for every OASIS field.
        output_dict["_items_detail"] = [
            {
                "item_code": item["item_code"],
                "value": item.get("value"),
                "rationale": item.get("rationale", ""),
                "confidence": item.get("confidence", "high"),
                "status": "completed",
            }
            for item in final_items
            if item.get("item_code") and not item["item_code"].startswith("_")
        ]

        return output_dict

    # ── Private helpers ────────────────────────────────────────────────────────────────────

    @staticmethod
    def _apply_phq2_gate(phq_items: list[dict]) -> list[dict]:
        """Enforce the CMS PHQ-2 screening gate on a list of PHQ item dicts.

        Rule: If D0150A1 + D0150B1 < 3 the two-item screen is negative — items C–I
        (both symptom-presence X1 and frequency X2 codes) must be null/not-assessed,
        and D0160 is recalculated using only items A and B.

        Edits item dicts in-place and returns the same list.
        """
        by_code = {item["item_code"]: item for item in phq_items}

        a1_raw = by_code.get("D0150A1", {}).get("value")
        b1_raw = by_code.get("D0150B1", {}).get("value")
        if a1_raw is None or b1_raw is None:
            # Incomplete PHQ data — cannot evaluate gate
            return phq_items

        try:
            screen_score = int(str(a1_raw)) + int(str(b1_raw))
        except (ValueError, TypeError):
            return phq_items

        if screen_score >= 3:
            # Gate not triggered — full PHQ-9 was administered
            return phq_items

        # Gate fires: null out items C–I (symptoms not assessed)
        downstream_letters = ["C", "D", "E", "F", "G", "H", "I"]
        for letter in downstream_letters:
            for suffix in ("1", "2"):
                code = f"D0150{letter}{suffix}"
                item = by_code.get(code)
                if item is not None:
                    item["value"] = None
                    item["rationale"] = (
                        f"PHQ-2 screening score (D0150A1={a1_raw} + D0150B1={b1_raw} = "
                        f"{screen_score}) < 3 — PHQ-9 items C–I are not administered "
                        f"(CMS skip-logic gate). Original gap_answers value nulled by "
                        f"oasis_gold_standard_generator._apply_phq2_gate()."
                    )
                    item["confidence"] = "high"

        # Recalculate D0160: sum of frequency (X2) only for items present (X1 != "0") among A and B
        freq_sum = 0
        for letter in ("A", "B"):
            symptom = by_code.get(f"D0150{letter}1", {}).get("value")
            freq = by_code.get(f"D0150{letter}2", {}).get("value")
            if symptom is not None and str(symptom).strip() != "0" and freq is not None:
                try:
                    freq_sum += int(str(freq))
                except (ValueError, TypeError):
                    pass

        d0160 = by_code.get("D0160")
        if d0160 is not None:
            old_value = d0160.get("value")
            d0160["value"] = str(freq_sum)
            d0160["rationale"] = (
                f"PHQ-2 gate applied: screen score {screen_score} < 3. "
                f"D0160 recalculated as sum of frequency codes for present items A–B only "
                f"(was {old_value} in gap_answers; corrected to {freq_sum})."
            )
            d0160["confidence"] = "high"

        logger.info(
            "PHQ-2 gate applied (screen=%d): items C–I nulled, D0160 corrected to %d",
            screen_score,
            freq_sum,
        )
        return phq_items

    def _copy_from_gap_answers(self, gap_answers: dict, codes: list[str]) -> list[dict]:
        """Copy a list of codes verbatim from gap_answers.

        Args:
            gap_answers: Full gap answers dict from Step 4.
            codes: List of OASIS item codes to copy.

        Returns:
            List of item dicts with source="gap_answers".
        """
        items: list[dict] = []
        for code in codes:
            answer = _lookup_gap_answer(gap_answers, code)
            if answer is not None:
                # Resolve human-readable question text from field map or gap_answers
                meta = None
                try:
                    from app.config.oasis_field_map import OASIS_FIELD_MAP
                    meta = OASIS_FIELD_MAP.get(code)
                except Exception:
                    pass
                question_text = (meta["question"] if meta and meta.get("question") else code)
                items.append({
                    "item_code": code,
                    "value": str(answer) if answer is not None else None,
                    "rationale": (
                        f"Copied verbatim from tap_tap_gap_answers.json (Step 4 assessment). "
                        f"Question: {question_text}"
                    ),
                    "confidence": "high",
                    "source": "gap_answers",
                })
            else:
                logger.warning(
                    "Step 6: %s not found in gap_answers — skipping",
                    code,
                )
        return items

    @staticmethod
    def _correct_bims_arithmetic(bims_items: list[dict]) -> list[dict]:
        """Enforce two-level BIMS arithmetic consistency.

        Rules:
          C0300 = C0300A + C0300B + C0300C  (range 0–6)
          C0400 = C0400A + C0400B + C0400C  (range 0–6)
          C0500 = C0200  + C0300  + C0400   (range 0–15)

        Corrects C0300, C0400, and C0500 in-place if they don't match their sub-sums.
        Sub-code values are authoritative; grouping codes are derived.
        """
        by_code = {item["item_code"]: item for item in bims_items}

        def _int(code: str) -> int | None:
            item = by_code.get(code)
            if item is None:
                return None
            try:
                return int(str(item.get("value", "")).strip())
            except (ValueError, TypeError):
                return None

        def _fix(code: str, expected: int, sub_expr: str) -> None:
            item = by_code.get(code)
            if item is None:
                by_code[code] = {
                    "item_code": code,
                    "value": str(expected),
                    "rationale": f"BIMS arithmetic correction: {sub_expr} = {expected}",
                    "confidence": "high",
                    "source": "gap_answers",
                }
            else:
                current = item.get("value")
                if str(current) != str(expected):
                    logger.warning(
                        "Step 6: BIMS arithmetic mismatch — %s=%s but %s=%d; correcting",
                        code, current, sub_expr, expected,
                    )
                    item["value"] = str(expected)
                    item["rationale"] = (
                        f"BIMS arithmetic correction: {sub_expr} = {expected} "
                        f"(gap_answers had {current})."
                    )

        # Derive C0300 from sub-codes
        c0300a, c0300b, c0300c = _int("C0300A"), _int("C0300B"), _int("C0300C")
        if None not in (c0300a, c0300b, c0300c):
            _fix("C0300", c0300a + c0300b + c0300c, "C0300A+C0300B+C0300C")  # type: ignore[operator]

        # Derive C0400 from sub-codes
        c0400a, c0400b, c0400c = _int("C0400A"), _int("C0400B"), _int("C0400C")
        if None not in (c0400a, c0400b, c0400c):
            _fix("C0400", c0400a + c0400b + c0400c, "C0400A+C0400B+C0400C")  # type: ignore[operator]

        # Derive C0500 from C0200 + corrected C0300 + corrected C0400
        c0200 = _int("C0200")
        c0300 = _int("C0300")   # may have just been corrected
        c0400 = _int("C0400")   # may have just been corrected
        if None not in (c0200, c0300, c0400):
            _fix("C0500", c0200 + c0300 + c0400, "C0200+C0300+C0400")  # type: ignore[operator]

        # Return merged list (by_code may have new keys not in original list)
        return list(by_code.values())

    def _expand_gg_adl_from_gap_answers(self, gap_answers: dict) -> list[dict]:
        """Derive GG0130 X1 admission codes, GG0170 X1 admission codes, and M-ADL codes from
        Step 4 gap answers.

        PRD rule: GG admission performance values ARE validated in Step 4 and must
        propagate unchanged into the gold standard.  This method is authoritative —
        the LLM must not override these values.

        GG0130 is stored as a grouped dict {"Eating": "05", ...}; each label maps to
        a specific X1 code.  GG0170 is stored as {"A": "04", ...}; each key maps to
        the corresponding X1 code.  M-ADL codes are stored as individual entries.
        """
        items: list[dict] = []

        # ── GG0130 Self-Care X1 (admission performance) ───────────────────────────────────
        gg0130_letters = set()
        for letter_or_letters in GG0130_LABEL_TO_LETTER.values():
            if isinstance(letter_or_letters, list):
                gg0130_letters.update(letter_or_letters)
            else:
                gg0130_letters.add(letter_or_letters)

        gg0130_found = False
        for letter in sorted(gg0130_letters):
            code = f"GG0130{letter}1"
            val = _lookup_gap_answer(gap_answers, code)
            if val is not None:
                gg0130_found = True
                items.append({
                    "item_code": code,
                    "value": str(val),
                    "rationale": (
                        f"Copied verbatim from tap_tap_gap_answers.json (Step 4 assessment). "
                        f"PRD: GG admission performance is validated in Step 4."
                    ),
                    "confidence": "high",
                    "source": "gap_answers",
                })
        
        if not gg0130_found:
            # Fallback: old-format gap_answers store GG0130 with root field_code "GG0130"
            # but encode the sub-code letter in the title (e.g. "Self-Care: ... - GG0130A").
            seen_codes: set[str] = set()
            for section in gap_answers.get("sections", []):
                for q in section.get("questions", []):
                    if "GG0130" not in q.get("field_codes", []):
                        continue
                    answer = q.get("answer")
                    if answer is None:
                        continue
                    title = q.get("title", "")
                    m = re.search(r"\bGG0130([A-G])\b", title, re.IGNORECASE)
                    if not m:
                        continue
                    letter = m.group(1).upper()
                    suffix = "2" if "discharge" in title.lower() else "1"
                    code = f"GG0130{letter}{suffix}"
                    if code in seen_codes:
                        continue
                    seen_codes.add(code)
                    gg0130_found = True
                    items.append({
                        "item_code": code,
                        "value": str(answer),
                        "rationale": (
                            "Parsed from legacy gap_answers title (Step 4 assessment). "
                            "PRD: GG admission performance is validated in Step 4."
                        ),
                        "confidence": "high",
                        "source": "gap_answers",
                    })
            if not gg0130_found:
                logger.warning(
                    "Step 6: No GG0130 codes found in gap_answers — "
                    "GG0130 X1 codes will fall through to LLM"
                )

        # ── GG0170 Mobility X1 (admission performance) ────────────────────────────────────
        gg0170_letters = set(GG0170_KEY_TO_LETTER.values())
        gg0170_found = False
        for letter in sorted(gg0170_letters):
            code = f"GG0170{letter}1"
            val = _lookup_gap_answer(gap_answers, code)
            if val is not None:
                gg0170_found = True
                items.append({
                    "item_code": code,
                    "value": str(val),
                    "rationale": (
                        f"Copied verbatim from tap_tap_gap_answers.json (Step 4 assessment). "
                        f"PRD: GG admission performance is validated in Step 4."
                    ),
                    "confidence": "high",
                    "source": "gap_answers",
                })

        if not gg0170_found:
            # Fallback: old-format gap_answers encode letter + admission/discharge in titles
            # e.g. "Mobility: ... - GG0170A_admission" or "GG0170A_discharge"
            # Note: use non-greedy match without trailing \b because titles have 'A_admission'
            # where '_' is a word char and would break \b.
            seen_codes_170: set[str] = set()
            for section in gap_answers.get("sections", []):
                for q in section.get("questions", []):
                    if "GG0170" not in q.get("field_codes", []):
                        continue
                    answer = q.get("answer")
                    if answer is None:
                        continue
                    title = q.get("title", "")
                    m = re.search(r"GG0170(RR|[A-P])(?=[^A-Z]|$)", title, re.IGNORECASE)
                    if not m:
                        continue
                    letter = m.group(1).upper()
                    # Check for '_discharge' AFTER the letter (not just 'discharge' anywhere
                    # in the title, since titles read "... and Discharge Goals - GG0170A_admission").
                    tail = title[m.end():]
                    suffix = "2" if tail.lower().startswith("_discharge") else "1"
                    code = f"GG0170{letter}{suffix}"
                    if code in seen_codes_170:
                        continue
                    seen_codes_170.add(code)
                    gg0170_found = True
                    items.append({
                        "item_code": code,
                        "value": str(answer),
                        "rationale": (
                            "Parsed from legacy gap_answers title (Step 4 assessment). "
                            "PRD: GG admission performance is validated in Step 4."
                        ),
                        "confidence": "high",
                        "source": "gap_answers",
                    })
            if not gg0170_found:
                logger.warning(
                    "Step 6: No GG0170 codes found in gap_answers — "
                    "GG0170 X1 codes will fall through to LLM"
                )

        # ── ADL M-codes ───────────────────────────────────────────────────────────────────
        for code in ADL_COPY_CODES:
            answer = _lookup_gap_answer(gap_answers, code)
            if answer is not None:
                items.append({
                    "item_code": code,
                    "value": str(answer) if answer is not None else None,
                    "rationale": (
                        f"Copied verbatim from tap_tap_gap_answers.json (Step 4 assessment). "
                        f"Question: {code}"
                    ),
                    "confidence": "high",
                    "source": "gap_answers",
                })
            else:
                logger.warning(
                    "Step 6: %s not found in gap_answers — skipping",
                    code,
                )

        logger.info(
            "Step 6: _expand_gg_adl_from_gap_answers produced %d items "
            "(GG0130=%d, GG0170=%d, ADL=%d)",
            len(items),
            sum(1 for i in items if i["item_code"].startswith("GG0130")),
            sum(1 for i in items if i["item_code"].startswith("GG0170")),
            sum(1 for i in items if not i["item_code"].startswith("GG")),
        )
        return items

    @staticmethod
    def _summarise_medication_list(medication_list: dict) -> str:
        """Extract a compact summary of active medications from Layer 1 for prompt context."""
        try:
            layer1 = medication_list.get("layer1") or medication_list
            meds = layer1.get("medications") or []
            if meds:
                names = []
                for m in meds[:15]:
                    name = (
                        m.get("name")
                        or m.get("medication_name")
                        or m.get("drug_name")
                        or str(m)
                    )
                    if name:
                        names.append(name)
                return "Active medications: " + ", ".join(names)
        except Exception:
            pass
        return "(Medication list unavailable)"

    # ── N0415 Multi-Flag Decomposition ────────────────────────────────────────────────────

    # ── N0415 Multi-Flag Derivation ─────────────────────────────────────────────────────

    _N0415_ALL_CODES: list[str] = [
        "N0415A", "N0415B", "N0415C", "N0415D",
        "N0415E", "N0415F", "N0415G", "N0415H", "N0415I",
    ]
    _N0415_CODE_LABELS: dict[str, str] = {
        "N0415A": "Antipsychotic",
        "N0415B": "Anticoagulant",
        "N0415C": "Antibiotic",
        "N0415D": "Antiplatelet",
        "N0415E": "Hypoglycemic (Insulin/Oral)",
        "N0415F": "Cardiovascular (Narrow TI)",
        "N0415G": "Diuretic",
        "N0415H": "Opioid",
        "N0415I": "None of above high-risk drugs",
    }
    # Correct drug-name → N0415 code mapping (case-insensitive substring match)
    _N0415_MED_NAME_TO_CODE: dict[str, str] = {
        # N0415A Antipsychotic
        "haloperidol": "N0415A", "quetiapine": "N0415A", "risperidone": "N0415A",
        "olanzapine": "N0415A", "aripiprazole": "N0415A",
        # N0415B Anticoagulant
        "warfarin": "N0415B", "apixaban": "N0415B", "rivaroxaban": "N0415B",
        "dabigatran": "N0415B", "enoxaparin": "N0415B", "heparin": "N0415B",
        # N0415C Antibiotic (systemic)
        "amoxicillin": "N0415C", "ciprofloxacin": "N0415C", "vancomycin": "N0415C",
        "azithromycin": "N0415C", "doxycycline": "N0415C", "levofloxacin": "N0415C",
        "cephalexin": "N0415C", "trimethoprim": "N0415C", "sulfamethoxazole": "N0415C",
        "metronidazole": "N0415C", "clindamycin": "N0415C", "nitrofurantoin": "N0415C",
        "ceftriaxone": "N0415C", "piperacillin": "N0415C", "meropenem": "N0415C",
        # N0415D Antiplatelet
        "clopidogrel": "N0415D", "ticagrelor": "N0415D", "prasugrel": "N0415D",
        # aspirin ≥325mg handled separately in _derive_n0415_from_medication_list
        # N0415E Hypoglycemic
        "insulin": "N0415E", "metformin": "N0415E", "glipizide": "N0415E",
        "sitagliptin": "N0415E", "empagliflozin": "N0415E", "glimepiride": "N0415E",
        "pioglitazone": "N0415E", "canagliflozin": "N0415E", "dapagliflozin": "N0415E",
        "liraglutide": "N0415E", "dulaglutide": "N0415E", "semaglutide": "N0415E",
        "glyburide": "N0415E", "glipizide": "N0415E",
        # N0415F Cardiovascular (narrow TI)
        "digoxin": "N0415F", "amiodarone": "N0415F", "flecainide": "N0415F",
        "sotalol": "N0415F", "dronedarone": "N0415F",
        # N0415G Diuretic
        "furosemide": "N0415G", "torsemide": "N0415G", "bumetanide": "N0415G",
        "hydrochlorothiazide": "N0415G", "chlorthalidone": "N0415G",
        "spironolactone": "N0415G", "metolazone": "N0415G",
        # N0415H Opioid
        "oxycodone": "N0415H", "morphine": "N0415H", "hydromorphone": "N0415H",
        "fentanyl": "N0415H", "tramadol": "N0415H", "codeine": "N0415H",
        "buprenorphine": "N0415H", "methadone": "N0415H", "hydrocodone": "N0415H",
        "oxymorphone": "N0415H",
    }
    # Legacy drug-class string → correct N0415 code (for old gap_answers array format)
    _N0415_DRUG_CLASS_MAP: dict[str, str] = {
        "Antipsychotic": "N0415A",
        "Anticoagulant": "N0415B",
        "Antibiotic": "N0415C",
        "Antiplatelet": "N0415D",
        "Hypoglycemic": "N0415E",
        "Insulin": "N0415E",
        "Cardiovascular": "N0415F",
        "Digoxin": "N0415F",
        "Narrow Therapeutic": "N0415F",
        "Diuretic": "N0415G",
        "Opioid": "N0415H",
    }

    def _derive_n0415_from_gap_sub_codes(self, gap_answers: dict) -> list[dict] | None:
        """Read N0415A–I individual sub-codes from gap_answers (new prompt format).

        Returns a list of 9 items if all sub-codes are present, None if any are missing
        (so the caller can fall back to medication-list derivation).
        """
        items: list[dict] = []
        for code in self._N0415_ALL_CODES:
            val = _lookup_gap_answer(gap_answers, code)
            if val is None:
                logger.debug(
                    "Step 6: N0415 sub-code %s not found in gap_answers — falling back to med list",
                    code,
                )
                return None
            items.append({
                "item_code": code,
                "value": str(val),
                "rationale": (
                    f"Propagated verbatim from Step 4 gap assessment. "
                    f"{self._N0415_CODE_LABELS.get(code, code)}: "
                    f"{'present' if str(val) == '1' else 'absent'}."
                ),
                "confidence": "high",
                "source": "gap_answers",
            })
        logger.info("Step 6: N0415 A–I read from gap_answers sub-codes")
        return items

    def _derive_n0415_from_medication_list(self, medication_list: dict | None) -> list[dict] | None:
        """Derive N0415A–I flags deterministically from the medication_list dict.

        Returns a full 9-item list, or None if medication_list is empty/unavailable.
        """
        if not medication_list:
            return None
        try:
            layer1 = medication_list.get("layer1") or medication_list
            meds = layer1.get("medications") or []
            if not meds:
                return None
        except Exception:
            return None

        flags: dict[str, str] = {c: "0" for c in self._N0415_ALL_CODES}
        matched: list[str] = []
        try:
            for med in meds:
                name = (
                    med.get("name") or med.get("medication_name") or med.get("drug_name") or ""
                ).lower()
                dose_str = str(med.get("dose") or med.get("dosage") or "").lower()
                for keyword, code in self._N0415_MED_NAME_TO_CODE.items():
                    if keyword in name:
                        if flags[code] == "0":
                            matched.append(f"{name}→{code}")
                        flags[code] = "1"
                        break
                # Aspirin ≥325 mg → antiplatelet
                if "aspirin" in name:
                    try:
                        dose_val = float("".join(c for c in dose_str if c.isdigit() or c == "."))
                        if dose_val >= 325:
                            if flags["N0415D"] == "0":
                                matched.append(f"aspirin {dose_val}mg→N0415D")
                            flags["N0415D"] = "1"
                    except (ValueError, TypeError):
                        pass
        except Exception as exc:
            logger.warning("Step 6: N0415 medication scan error: %s", exc)

        # N0415I = "1" only when ALL A–H are "0"
        if all(flags[c] == "0" for c in self._N0415_ALL_CODES[:-1]):
            flags["N0415I"] = "1"
        logger.info(
            "Step 6: N0415 derived from medication_list — matched: %s, flags: %s",
            matched,
            {k: v for k, v in flags.items() if v == "1"},
        )
        items: list[dict] = []
        for code in self._N0415_ALL_CODES:
            items.append({
                "item_code": code,
                "value": flags[code],
                "rationale": (
                    f"N0415 flag deterministically derived from medication_list. "
                    f"{self._N0415_CODE_LABELS.get(code, code)}: "
                    f"{'present' if flags[code] == '1' else 'absent'}."
                ),
                "confidence": "high",
                "source": "medication_list",
            })
        return items

    def _decompose_n0415_from_gap_answers(self, gap_answers: dict) -> list[dict]:
        """Legacy fallback: derive N0415 flags from the old gap_answers N0415 array format.

        Supports old format where N0415 was stored as an array of
        {drug_class, medication, indication} objects.  Always returns all 9 flags.
        """
        n0415_answer = _lookup_gap_answer(gap_answers, "N0415")

        flags: dict[str, str] = {c: "0" for c in self._N0415_ALL_CODES}
        found_classes: list[str] = []

        if isinstance(n0415_answer, list):
            for entry in n0415_answer:
                drug_class = ""
                if isinstance(entry, dict):
                    drug_class = str(entry.get("drug_class", "")).strip()
                elif isinstance(entry, str):
                    drug_class = entry.strip()
                mapped = self._N0415_DRUG_CLASS_MAP.get(drug_class)
                if mapped:
                    flags[mapped] = "1"
                    found_classes.append(drug_class)
        elif isinstance(n0415_answer, str) and n0415_answer:
            # Single string drug class
            mapped = self._N0415_DRUG_CLASS_MAP.get(n0415_answer.strip())
            if mapped:
                flags[mapped] = "1"
                found_classes.append(n0415_answer)

        # N0415I = "1" only when ALL A–H are "0"
        if all(flags[c] == "0" for c in self._N0415_ALL_CODES[:-1]):
            flags["N0415I"] = "1"

        logger.info(
            "Step 6: N0415 legacy decompose — drug classes found: %s → flags: %s",
            found_classes,
            {k: v for k, v in flags.items() if v == "1"},
        )
        items: list[dict] = []
        for code in self._N0415_ALL_CODES:
            items.append({
                "item_code": code,
                "value": flags[code],
                "rationale": (
                    f"Deterministically derived from Step 4 gap_answers N0415 legacy array. "
                    f"{self._N0415_CODE_LABELS.get(code, code)}: "
                    f"{'present' if flags[code] == '1' else 'absent'}."
                ),
                "confidence": "high",
                "source": "gap_answers",
            })
        return items

    @staticmethod
    def _build_gap_context(gap_answers: dict) -> str:
        """Build a comprehensive Step 4 context block for the LLM prompt.

        Includes BIMS total, PHQ total, ALL individual GG0130/GG0170 sub-items,
        ADL M-codes, and key functional codes.  The LLM MUST use these as the
        authoritative source — it must not re-derive GG discharge goals
        independently (PRD Step 4 rule: GG goals require clinical judgment and
        are never extractable from referral/scribe).
        """
        lines: list[str] = []

        # ── Top-level scores ───────────────────────────────────────────────────
        for code, label in [
            ("C0500", "BIMS Total (C0500)"),
            ("D0160", "PHQ-9 Total (D0160)"),
        ]:
            val = _lookup_gap_answer(gap_answers, code)
            if val is not None:
                lines.append(f"{label}: {val}")

        # ── GG0130 Self-Care — expand grouped dict or individual sub-codes ────
        gg0130_answer = _lookup_gap_answer(gap_answers, "GG0130")
        if gg0130_answer and isinstance(gg0130_answer, dict):
            # Step 4 stores as a grouped object: {"Eating": "05", "Oral Hygiene": "04", ...}
            lines.append("GG0130 Self-Care (Step 4 grouped answers):")
            for sub, val in gg0130_answer.items():
                lines.append(f"  GG0130 {sub}: {val}")
        else:
            # Try individual sub-codes (if stored with specific field_codes)
            gg0130_lines = []
            for letter in ["A", "B", "C", "D", "E", "F", "G"]:
                for suffix in ["1", "2"]:
                    code = f"GG0130{letter}{suffix}"
                    val = _lookup_gap_answer(gap_answers, code)
                    if val is not None:
                        gg0130_lines.append(f"  {code}: {val}")
            if gg0130_lines:
                lines.append("GG0130 Self-Care (Step 4 answers):")
                lines.extend(gg0130_lines)
            else:
                # Fallback: parse letter+suffix from question titles (legacy format)
                seen_130: set[str] = set()
                parsed_130: list[str] = []
                for section in gap_answers.get("sections", []):
                    for q in section.get("questions", []):
                        if "GG0130" not in q.get("field_codes", []):
                            continue
                        answer = q.get("answer")
                        if answer is None:
                            continue
                        title = q.get("title", "")
                        m = re.search(r"\bGG0130([A-G])\b", title, re.IGNORECASE)
                        if not m:
                            continue
                        letter = m.group(1).upper()
                        suffix = "2" if "discharge" in title.lower() else "1"
                        code = f"GG0130{letter}{suffix}"
                        if code not in seen_130:
                            seen_130.add(code)
                            parsed_130.append(f"  {code}: {answer}")
                if parsed_130:
                    lines.append("GG0130 Self-Care (Step 4 answers):")
                    lines.extend(parsed_130)

        # ── GG0170 Mobility — expand grouped dict or individual sub-codes ─────
        gg0170_answer = _lookup_gap_answer(gap_answers, "GG0170")
        if gg0170_answer and isinstance(gg0170_answer, dict):
            lines.append("GG0170 Mobility (Step 4 grouped answers):")
            for sub, val in gg0170_answer.items():
                lines.append(f"  GG0170 {sub}: {val}")
        else:
            gg0170_lines = []
            for letter in ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P"]:
                for suffix in ["1", "2"]:
                    code = f"GG0170{letter}{suffix}"
                    val = _lookup_gap_answer(gap_answers, code)
                    if val is not None:
                        gg0170_lines.append(f"  {code}: {val}")
            # RR only has suffix 1 (admission only)
            rr1_val = _lookup_gap_answer(gap_answers, "GG0170RR1")
            if rr1_val is not None:
                gg0170_lines.append(f"  GG0170RR1: {rr1_val}")
            if gg0170_lines:
                lines.append("GG0170 Mobility (Step 4 answers):")
                lines.extend(gg0170_lines)
            else:
                # Fallback: parse from titles (legacy format)
                seen_170: set[str] = set()
                parsed_170: list[str] = []
                for section in gap_answers.get("sections", []):
                    for q in section.get("questions", []):
                        if "GG0170" not in q.get("field_codes", []):
                            continue
                        answer = q.get("answer")
                        if answer is None:
                            continue
                        title = q.get("title", "")
                        m = re.search(r"GG0170(RR|[A-P])(?=[^A-Z]|$)", title, re.IGNORECASE)
                        if not m:
                            continue
                        letter = m.group(1).upper()
                        tail = title[m.end():]
                        suffix = "2" if tail.lower().startswith("_discharge") else "1"
                        code = f"GG0170{letter}{suffix}"
                        if code not in seen_170:
                            seen_170.add(code)
                            parsed_170.append(f"  {code}: {answer}")
                if parsed_170:
                    lines.append("GG0170 Mobility (Step 4 answers):")
                    lines.extend(parsed_170)

        # GG0170C prior function
        gg0170c = _lookup_gap_answer(gap_answers, "GG0170C")
        if gg0170c is not None:
            lines.append(f"GG0170C prior walking: {gg0170c}")

        # ── GG0100 Prior Functioning ──────────────────────────────────────────
        gg0100_answer = _lookup_gap_answer(gap_answers, "GG0100")
        if gg0100_answer and isinstance(gg0100_answer, dict):
            lines.append("GG0100 Prior Functioning (Step 4):")
            for sub, val in gg0100_answer.items():
                lines.append(f"  {sub}: {val}")
        else:
            for letter in ["A", "B", "C", "D"]:
                code = f"GG0100{letter}"
                val = _lookup_gap_answer(gap_answers, code)
                if val is not None:
                    lines.append(f"  {code}: {val}")

        # ── ADL M-codes from Step 4 ───────────────────────────────────────────
        adl_codes = [
            "M1800", "M1810", "M1820", "M1830", "M1840",
            "M1845", "M1850", "M1860", "M1870", "M1880",
            "M1890", "M1900", "M1910",
        ]
        adl_lines = []
        for code in adl_codes:
            val = _lookup_gap_answer(gap_answers, code)
            if val is not None:
                adl_lines.append(f"  {code}: {val}")
        if adl_lines:
            lines.append("ADL M-codes (Step 4):")
            lines.extend(adl_lines)

        # ── Cognitive / Behavioral ────────────────────────────────────────────
        for code in ["M1700", "M1710", "M1720", "M1740", "M1400"]:
            val = _lookup_gap_answer(gap_answers, code)
            if val is not None:
                lines.append(f"{code}: {val}")

        return "\n".join(lines) if lines else "(No gap assessment context available)"

    def _generate_and_fix_section_batch(
        self,
        *,
        codes: list[str],
        section_name: str,
        archetype: str,
        diagnosis_context: str,
        referral_text: str,
        scribe_section: str,
        medication_json: str,
        gap_context: str,
        has_scribe: str,
        model_id: str,
        audit_context: str | None = None,
    ) -> list[dict]:
        """Generate a gold standard batch then validate and fix if needed.

        Implements the Generate → Validate → Fix loop for Step 6 section batches:
          1. LLM call with section-specific focused prompt.
          2. Python validators check the flat output dict.
          3. If violations found, one LLM fix call patches only the affected fields.

        Returns a list of item dicts consistent with the existing _run_llm_batch contract.
        """
        raw_items = self._run_llm_batch(
            codes=codes,
            section_name=section_name,
            archetype=archetype,
            diagnosis_context=diagnosis_context,
            referral_text=referral_text,
            scribe_section=scribe_section,
            medication_json=medication_json,
            gap_context=gap_context,
            has_scribe=has_scribe,
            model_id=model_id,
            audit_context=audit_context,
        )

        # Build flat {code: value} for validators
        flat = {
            item["item_code"]: item.get("value")
            for item in raw_items
            if isinstance(item, dict) and "item_code" in item
        }
        violations = validate_batch(flat, section_name)
        if not violations:
            return raw_items

        # ── Fix pass ─────────────────────────────────────────────────────────
        logger.warning(
            "Step 6 section=%s: %d violation(s) — running fix pass",
            section_name,
            len(violations),
        )
        fix_prompt = GOLD_SECTION_FIX_PROMPT.format(
            section_name=section_name,
            violations_list="\n".join(f"- {v}" for v in violations),
            original_items_json=json.dumps(flat, indent=2),
            archetype=archetype,
            diagnosis_context=diagnosis_context,
            medication_json=medication_json,
            gap_context=gap_context,
        )
        try:
            fix_response = self.bedrock.invoke_json(
                prompt=fix_prompt,
                model_id=model_id,
                max_tokens=2048,
            )
            fix_raw = json.loads(extract_json_object(fix_response["text"].strip()))
        except Exception as exc:
            logger.error("Step 6 section=%s fix parse failed (%s) — keeping original", section_name, exc)
            return raw_items

        if not isinstance(fix_raw, dict):
            return raw_items

        # Build an index of existing items for fast lookup
        item_index = {item["item_code"]: item for item in raw_items if "item_code" in item}
        for code, corrected_value in fix_raw.items():
            code_upper = code.strip().upper()
            if code_upper in item_index:
                item_index[code_upper]["value"] = corrected_value
                item_index[code_upper]["rationale"] = (
                    item_index[code_upper].get("rationale", "")
                    + f" [Fix applied: {', '.join(violations)}]"
                )
            else:
                # New field injected by fix (e.g. missing N0415 sub-code)
                item_index[code_upper] = {
                    "item_code": code_upper,
                    "value": corrected_value,
                    "rationale": f"Added by fix pass: {', '.join(violations)}",
                    "confidence": "high",
                    "source": "fix",
                }
        logger.info("Step 6 section=%s: fix pass applied %d correction(s)", section_name, len(fix_raw))
        return list(item_index.values())

    def _run_llm_batch(
        self,
        *,
        codes: list[str],
        section_name: str,
        archetype: str,
        diagnosis_context: str,
        referral_text: str,
        scribe_section: str,
        medication_json: str,
        gap_context: str,
        has_scribe: str,
        model_id: str,
        audit_context: str | None = None,
    ) -> list[dict]:
        """Run one LLM batch and return a list of OASIS item dicts.

        Args:
            codes: List of OASIS item codes for this batch.
            section_name: Human-readable batch name used in logging and prompt.
            archetype: Patient clinical archetype string.
            diagnosis_context: Primary diagnosis description.
            referral_text: Full referral packet text.
            scribe_section: Formatted ambient scribe text block (or placeholder string).
            medication_json: Compact medication list summary string.
            gap_context: Step 4 gap context block string.
            has_scribe: "Yes" or "No" string for the prompt.
            model_id: AWS Bedrock model identifier.

        Returns:
            List of item dicts (item_code, value, rationale, confidence, source).
        """
        # Select focused section prompt; fall back to monolithic prompt for unknown sections
        prompt_template = GOLD_SECTION_PROMPT_MAP.get(section_name, OASIS_GOLD_STANDARD_PROMPT)

        # Build format kwargs — Batch E needs {medication_json}; others typically don't.
        fmt_kwargs: dict = {
            "archetype": archetype,
            "diagnosis_context": diagnosis_context,
            "has_scribe": has_scribe,
            "section_name": section_name,
            "referral_text": referral_text,
            "scribe_section": scribe_section,
            "gap_context": gap_context,
            "field_codes_json": json.dumps(codes, indent=2),
        }
        if "{medication_json}" in prompt_template:
            fmt_kwargs["medication_json"] = medication_json

        prompt = prompt_template.format(**fmt_kwargs)

        # Append medication list for batches that don't already embed it (A–D).
        # RAG is skipped in patient-dataset-generation — all source docs are injected
        # directly. Medication is a source doc and must reach every batch since it
        # affects fields across all sections (e.g. M1033 risk factors, M1400 dyspnea).
        if "{medication_json}" not in prompt_template and medication_json:
            prompt += f"\n\n--- MEDICATION LIST (reference for all fields) ---\n{medication_json}\n"

        # Append per-field OASIS coding guidance extracted from oasis_config.json.
        # This injects the same group_guidance used by oasis-llm-processor and
        # prompt-improvement into the gold-standard generation step so the LLM
        # produces consistent, rule-conformant values.
        oasis_guidance_block = self._build_oasis_guidance_for_codes(codes)
        if oasis_guidance_block:
            prompt += (
                "\n\n--- OASIS CODING GUIDANCE (per-field rules from oasis_config) ---\n"
                + oasis_guidance_block
                + "\n"
            )

        if audit_context:
            prompt += f"\n\n{audit_context}"

        response = self.bedrock.invoke_json(
            prompt=prompt,
            model_id=model_id,
            max_tokens=4096,
        )
        text = response["text"].strip()

        try:
            raw = json.loads(extract_json_object(text))
        except Exception as exc:
            logger.error(
                "Step 6 batch %s JSON parse failed (%s) — attempting repair",
                section_name,
                exc,
            )
            raw = repair_truncated_json(text)

        def _flatten_data(d: Any, prefix: str = "") -> dict[str, str]:
            flat_dict = {}
            if isinstance(d, dict):
                for k, v in d.items():
                    flat_dict.update(_flatten_data(v, prefix + k))
            elif isinstance(d, list):
                for i, item in enumerate(d):
                    flat_dict.update(_flatten_data(item, f"{prefix}_{i+1}"))
            else:
                if d is not None and str(d).strip() != "":
                    flat_dict[prefix] = str(d)
            return flat_dict

        if not isinstance(raw, list):
            logger.warning("Step 6 batch %s: LLM returned non-array — wrapping", section_name)
        if isinstance(raw, dict):
            # Flatten any nested structures into flat standard key-value map
            flat_raw = _flatten_data(raw)
            # Re-map to the list of dictionaries that the rest of the function evaluates
            raw_list = [{"item_code": k, "value": v} for k, v in flat_raw.items()]
        elif isinstance(raw, list):
            # Fallback if LLM inexplicably returned a list
            raw_list = []
            for item in raw:
                if isinstance(item, dict) and "item_code" in item and "value" in item:
                    raw_list.append(item)
                else:
                    flat_item = _flatten_data(item)
                    for k, v in flat_item.items():
                        raw_list.append({"item_code": k, "value": v})
        else:
            raw_list = []
            logger.warning("Step 6 batch %s: LLM returned unexpected structure.", section_name)

        raw = raw_list

        seen_codes: set[str] = set()
        batch_items: list[dict] = []
        for entry in raw:
            if not isinstance(entry, dict):
                continue
            code = str(entry.get("item_code") or "").strip().upper()
            if not code or code in seen_codes:
                continue
            seen_codes.add(code)
            batch_items.append({
                "item_code": code,
                "value": entry.get("value"),
            })

        # Fill in placeholder items for any codes not returned by the LLM.
        for code in codes:
            if code not in seen_codes:
                logger.warning(
                    "Step 6 batch %s: no item for %s — inserting placeholder",
                    section_name,
                    code,
                )
                batch_items.append({
                    "item_code": code,
                    "value": None,
                    "rationale": f"Not returned by LLM for batch {section_name}",
                    "confidence": "low",
                    "source": "llm",
                })

        return batch_items

    def _apply_skip_logic(
        self, item_map: dict[str, dict]
    ) -> tuple[dict[str, dict], list[str]]:
        """Apply 8 deterministic CMS skip-logic rules.

        Args:
            item_map: Dict of item_code -> item dict.

        Returns:
            Tuple of (modified item_map, list of rule names applied).
        """
        rules_applied: list[str] = []

        # ── 1. BIMS_GATE: C0100=0 → null BIMS sub-scores ─────────────────────────────────
        # Only apply when C0100 was generated by the LLM — if it was copied verbatim from
        # gap_answers (source="gap_answers"), gap is authoritative and we preserve sub-scores.
        c0100_item = item_map.get("C0100")
        c0100_from_gap = c0100_item and c0100_item.get("source") == "gap_answers"
        if _item_value(item_map, "C0100") == "0" and not c0100_from_gap:
            bims_downstream = [
                "C0200", "C0300A", "C0300B", "C0300C",
                "C0400A", "C0400B", "C0400C", "C0500",
            ]
            modified = any(
                item_map[c].get("value") is not None
                for c in bims_downstream
                if c in item_map
            )
            for code in bims_downstream:
                if code in item_map:
                    item_map[code]["value"] = None
                    item_map[code]["rationale"] = "Skip: C0100=0 (BIMS was not administered)"
            if modified:
                rules_applied.append("BIMS_GATE")

        # ── 2. PHQ_GATE: D0150A1=9 AND D0150B1=9 → null all downstream PHQ ──────────────
        if _item_value(item_map, "D0150A1") == "9" and _item_value(item_map, "D0150B1") == "9":
            phq_downstream = [
                "D0150C1", "D0150C2", "D0150D1", "D0150D2",
                "D0150E1", "D0150E2", "D0150F1", "D0150F2",
                "D0150G1", "D0150G2", "D0150H1", "D0150H2",
                "D0150I1", "D0150I2", "D0160",
            ]
            for code in phq_downstream:
                if code in item_map:
                    item_map[code]["value"] = None
                    item_map[code]["rationale"] = (
                        "Skip: PHQ-2 screening negative (D0150A1=9, D0150B1=9)"
                    )
            rules_applied.append("PHQ_GATE")

        # ── 3. PHQ_COL2_GATE: each D0150X1=0 → D0150X2=null ─────────────────────────────
        phq_col2_modified = False
        for letter in ["A", "B", "C", "D", "E", "F", "G", "H", "I"]:
            col1 = f"D0150{letter}1"
            col2 = f"D0150{letter}2"
            if _item_value(item_map, col1) == "0" and col2 in item_map:
                item_map[col2]["value"] = None
                item_map[col2]["rationale"] = (
                    f"Skip: {col1}=0 (symptom not present; frequency column N/A)"
                )
                phq_col2_modified = True
        if phq_col2_modified:
            rules_applied.append("PHQ_COL2_GATE")

        # ── 4. M1306_ULCER: M1306=0 → wound staging items = "0" ─────────────────────────
        if _item_value(item_map, "M1306") == "0":
            for code in ["M1311", "M1312", "M1313", "M1314"]:
                if code in item_map:
                    item_map[code]["value"] = "0"
                    item_map[code]["rationale"] = (
                        "Skip: M1306=0 (no unhealed pressure ulcer at Stage 2+)"
                    )
            rules_applied.append("M1306_ULCER")

        # ── 5. M1330_STASIS: M1330=0 → null M1332, M1334 ────────────────────────────────
        if _item_value(item_map, "M1330") == "0":
            for code in ["M1332", "M1334"]:
                if code in item_map:
                    item_map[code]["value"] = None
                    item_map[code]["rationale"] = "Skip: M1330=0 (no stasis ulcer present)"
            rules_applied.append("M1330_STASIS")

        # ── 6. GG_WALK_HIERARCHY: GG0170I1 unable → skip J/K/L walk items ────────────────
        # Only override items that were NOT already sourced from gap_answers (gap is authoritative).
        i1_val = _item_value(item_map, "GG0170I1")
        if i1_val in {"07", "09", "10", "88"}:
            walk_modified = False
            for code in ["GG0170J1", "GG0170K1", "GG0170L1"]:
                target = item_map.get(code)
                if target and target.get("source") != "gap_answers":
                    target["value"] = "88"
                    target["rationale"] = (
                        f"Skip: GG0170I1={i1_val} — patient cannot walk 10 ft; "
                        "longer walking activities not attempted"
                    )
                    walk_modified = True
            if walk_modified:
                rules_applied.append("GG_WALK_HIERARCHY")

        # ── 7. GG_STAIR_HIERARCHY: GG0170M1 unable → skip N stair items ──────────────────
        # NOTE: GG0170O (Picking Up Object) is NOT a stair task — it is independent of M.
        # Only override GG0170N1 and only when not sourced from gap_answers.
        m1_val = _item_value(item_map, "GG0170M1")
        if m1_val in {"07", "09", "10", "88"}:
            stair_modified = False
            for code in ["GG0170N1"]:
                target = item_map.get(code)
                if target and target.get("source") != "gap_answers":
                    target["value"] = "88"
                    target["rationale"] = (
                        f"Skip: GG0170M1={m1_val} — patient cannot climb 4 steps; "
                        "12-step stair activity not attempted"
                    )
                    stair_modified = True
            if stair_modified:
                rules_applied.append("GG_STAIR_HIERARCHY")

        # ── 8. M1740_EXCLUSIVE: code "7" (None of above) is exclusive ────────────────────
        m1740_val = _item_value(item_map, "M1740")
        if m1740_val is not None and "7" in str(m1740_val):
            if "M1740" in item_map:
                item_map["M1740"]["value"] = "7"
                item_map["M1740"]["rationale"] = (
                    "M1740 None-of-above (7) is exclusive: other behavioral symptoms cleared"
                )
            rules_applied.append("M1740_EXCLUSIVE")

        return item_map, rules_applied

    def _build_validation(self, items: list[dict], rules_applied: list[str]) -> dict:
        """Build the validation block from the final item list.

        Args:
            items: Final sorted list of OASIS item dicts.
            rules_applied: List of skip-logic rule names that were applied.

        Returns:
            Dict with bims_verified, bims_score, phq_verified, phq_score,
            hip_score, hip_valid, skip_logic_applied.
        """
        item_map = {i["item_code"]: i for i in items}

        # BIMS score from C0500
        bims_score: int | None = None
        bims_verified = False
        c0500 = item_map.get("C0500")
        if c0500 and c0500.get("value") is not None:
            try:
                bims_score = int(str(c0500["value"]).strip().split()[0])
                bims_verified = 0 <= bims_score <= 15
            except (ValueError, TypeError):
                pass

        # PHQ score from D0160
        phq_score: int | None = None
        phq_verified = False
        d0160 = item_map.get("D0160")
        if d0160 and d0160.get("value") is not None:
            try:
                phq_score = int(str(d0160["value"]).strip().split()[0])
                phq_verified = 0 <= phq_score <= 27
            except (ValueError, TypeError):
                pass

        # HIP score from GG0130A1–E1
        hip_score, hip_valid = self._calculate_hip(item_map)

        return {
            "bims_verified": bims_verified,
            "bims_score": bims_score,
            "phq_verified": phq_verified,
            "phq_score": phq_score,
            "hip_score": hip_score,
            "hip_valid": hip_valid,
            "skip_logic_applied": rules_applied,
        }

    @staticmethod
    def _calculate_hip(item_map: dict[str, dict]) -> tuple:
        """Calculate HIP score: sum of GG0130A1–E1 self-care admission performance codes (5–30).

        Returns:
            Tuple of (hip_score: int | None, hip_valid: bool).
        """
        scores: list[int] = []
        for code in HIP_CODES:
            item = item_map.get(code)
            if item is None or item.get("value") is None:
                return None, False
            try:
                val = int(str(item["value"]).strip().split()[0])
                if not (1 <= val <= 6):
                    return None, False
                scores.append(val)
            except (ValueError, TypeError):
                return None, False
        return sum(scores), True

    def generate_fix(
        self,
        *,
        referral_text: str,
        ambient_scribe_text: str,
        medication_list_json: str,
        gap_answers_json: str,
        current_oasis_gold_standard_json: str,
        audit_conflicts_text: str,
        model_id: str,
    ) -> dict:
        """Produce a revised oasis_gold_standard.json that resolves LLM audit conflicts.

        Uses OASIS_GOLD_STANDARD_FIX_PROMPT which shows all existing documents +
        the audit conflict summary and asks for a targeted JSON revision.
        """
        from app.config.prompts import OASIS_GOLD_STANDARD_FIX_PROMPT
        prompt = OASIS_GOLD_STANDARD_FIX_PROMPT.format(
            referral_text=referral_text[:6000],
            ambient_scribe_text=ambient_scribe_text[:4000],
            medication_list_json=medication_list_json[:2000],
            gap_answers_json=gap_answers_json[:3000],
            current_oasis_gold_standard_json=current_oasis_gold_standard_json[:6000],
            audit_conflicts_text=audit_conflicts_text,
        )
        response = self.bedrock.invoke_json(
            prompt=prompt,
            model_id=model_id,
            max_tokens=4096,
        )
        text = response["text"].strip()
        try:
            result = json.loads(extract_json_object(text))
        except Exception as exc:
            logger.error("generate_fix JSON parse failed (%s) — attempting repair", exc)
            result = repair_truncated_json(text)
        if not isinstance(result, dict):
            raise ValueError(f"generate_fix returned non-dict: {type(result)}")
        return result
